// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4WQ1EFMzinHM1OirBmG-CaIs7peN23pc',
    appId: '1:840891291637:web:ddc447ff7f19a1f448f2bc',
    messagingSenderId: '840891291637',
    projectId: 'cs310-groupproject-flutter',
    authDomain: 'cs310-groupproject-flutter.firebaseapp.com',
    storageBucket: 'cs310-groupproject-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEyIYNNiM5EGjxLoizXAUZbj9mf-TrxPQ',
    appId: '1:840891291637:android:ed74975bf4d35a7148f2bc',
    messagingSenderId: '840891291637',
    projectId: 'cs310-groupproject-flutter',
    storageBucket: 'cs310-groupproject-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDq0hfuGBbpyyk2KPVfwueTc29L2nTbGqs',
    appId: '1:840891291637:ios:2aa49115127773e548f2bc',
    messagingSenderId: '840891291637',
    projectId: 'cs310-groupproject-flutter',
    storageBucket: 'cs310-groupproject-flutter.appspot.com',
    iosClientId: '840891291637-bbgfcleuj2fie8nud5nd7b4f38uurao2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterui',
  );
}
